apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-cartservice
spec:
  selector:
    matchLabels:
      app: eshop-cartservice
  template:
    metadata:
      labels:
        app: eshop-cartservice
    spec:
      containers:
        - name: eshop-cartservice
          image: gcr.io/architect-certification-289902/37/eshop-cartservice@sha256:08b29e21d7e1b3b9e8687cbcdde8139e0ab61270ec786c6379f648d4df02d0b8
          ports:
          - containerPort: 8091
          env:
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-cartservice
spec:
  type: ClusterIP
  selector:
    app: eshop-cartservice
  ports:
  - port: 8091