apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-productservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop-productservice
  template:
    metadata:
      labels:
        app: eshop-productservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: eshop-productservice
        image: gcr.io/architect-certification-289902/37/eshop-productservice@sha256:ffc9eacf0c1078895a480a7a7fdf2c979e8557469c10fe816a7ebcfc52b68ca0
        ports:
        - containerPort: 8092
        env:
        - name: PORT
          value: "8092"
        - name: INIT_DATA
          value: "true"
        - name: MONGO_URI
          value: "mongodb://mongodb-arbiter-headless.default.svc.cluster.local/?replicaSet=rs0"          
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-productservice
spec:
  type: ClusterIP
  selector:
    app: eshop-productservice
  ports:
  - name: api
    port: 8092
    targetPort: 8092
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: eshop-productservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eshop-productservice
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50